version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: docker pull evaldez/devop-node-circleci
            - run: docker run evaldez/devop-node-circleci npm test
