version: 2
jobs:
    build:
        docker:
            - image: evaldez/devop-node-circleci
        steps:
            - checkout
            - run: docker build -t evaldez/devop-node-circleci -f ../Dockerfile
            - run: docker run evaldez/devop-node-circleci npm test
